### ISSUE TITLE
edit destination details

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#16]
## Value Proposition
As a user, I want to edit the destination's details so that i can add or change dates, hotel and transport informations.
## Description
![image](https://user-images.githubusercontent.com/75478893/197202506-7fd88e78-79bd-44a4-94a9-d917aa0a4685.png)
## Acception Criteria
- [ ] An edit-button in upper right corner, that turns the details into a editable form (and back)
- [ ] The dates (start date / end date) can be changed by date-pickers
- [ ] Destination name, hotel and transport are text inputs

## Tasks
- [ ] Create a state for edit-mode
- [ ] Add an edit-button to upper right corner
- [ ] Create a function that toggles the edit-mode when clicked on edit-button
- [ ] Create text input fields for name, hotel, transport
- [ ] Create date picker inputs for date fields
- [ ] Change normal detail texts to input fields with save-button when edit-mode is enabled
- [ ] Create a function for the edit-button that updates the destination's details in localStorage, when edit-mode toggles off

**Comment by kai-franke** [comment]
Great story! 👍 😃 
Here are my remarks:
- You could add something like "the edited data is stored in localStorage" as an acception criteria.
- I don't understand the "save-button" (or I don't understand the function of the edit-button 😉 ). So after I changed the text inside the input fields, how will these changes be stored? Do I have to click a save-button or will a click on the edit-button store the changed inputs?

**Comment by sebsch1337** [comment]
Hey - thanks for the pre-weekend-review :)
1. Yes, i should explain how to save the data. Added an according line.
2. Oops, i forgot to delete the save-button part. There will be no save-button anymore. The details will be written to the localStorage after i toggle the edit mode off (klick edit-button again to exit the edit mode).
