### ISSUE TITLE
show to-do list

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#17]
## Value Proposition
As a user, I want to see a destinations to-do-list so that i have an overview of the things i plan to do .
## Description
<img width="339" alt="image" src="https://user-images.githubusercontent.com/75478893/197294913-ac7f5ad2-1128-49a1-aed9-239c29c5e5e8.png">

## Acception Criteria
- [x] A To-Do-List with label "To-Do"
- [x] One list item for each to-do with a checkbox that can be checked and unchecked
- [x] When a to-do is checked, the text turns gray and crossed out
- [x] The to-do's are saved as an object inside the according destination object

## Tasks
- [x] Add a DetailTitle component named "To-Do's" in the DetailSection component on details page
- [x] Create an array "toDos" inside the destinations items with dummy data as objects (id, description, checked)
- [x] Create a ul as styled ToDoWrapper component
- [x] Create a styled ToDoItem component with a checkbox and description text
- [x] Iterate through toDos object and return the ToDoItem component including props "key, id, description, checked"
- [x] Create a checked-prop-based conditioned style in ToDoItem to change checked items text to gray and crossed out
