### ISSUE TITLE
delete to-do item

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#18]
## Value Proposition
As a user, I want to delete a not needed to-do item so that my to-do list stays clean.
## Description
<img width="343" alt="image" src="https://user-images.githubusercontent.com/75478893/197298018-292aec82-6276-49e7-8c32-77b4071e4047.png">

## Acception Criteria
- [x] A delete button next to each to-do item
- [x] Deletes the to-do item from the list
- [x] Removes the to-do-object from the toDo-array in destinations state
## Tasks
- [x] Create a styled DeleteButton component with an icon
- [x] On details page, create a function that deletes the to-do item from the array in destinations state
- [x] Pass the delete-function as callback-function-prop to ToDoItem component
- [x] Place the DeleteButton inside the list item on the right side
- [x] Pass the delete-function with toDo-id to DeleteButton component
- [x] Create an onClick listener for the DeleteButton component that calls the delete-function
