### ISSUE TITLE
delete trip

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#19]
## Value Proposition
As a user, I want to delete trips so that my app will stay clean.
## Description
<img width="300" alt="image" src="https://user-images.githubusercontent.com/75478893/198569132-7abd6d33-bd80-4b31-8865-9bd7bae3b889.png">

## Acception Criteria
- [x] A footer on page bottom
- [x] A delete button with icon
- [x] This component can be used for trips and destinations
- [x] Click on "DELETE" button will delete the trip object
- [x] After deletion the app will navigate you to the trips overview page
## Tasks
- [x] Create a styled StyledFooter component
- [x] Create a styled DeleteButton component with an icon 
- [x] Add the StyledFooter to destinations page 
- [x] Add the DeleteButton to the StyledFooter component
- [x] On destinations page, write a function that deletes a trip by id and navigates to trips page
- [x] Pass the function to the StyledFooter and DeleteButton component
- [x] Set an onClick event to the DeleteButton that calls the passed delete-function with the passed id
- [x] Validate deletion in a modal
