### ISSUE TITLE
show trips

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#2]
## Value Proposition
As a user, I want to see my travel destination countries including duration, so that i have an overview of my upcoming trips.
## Description
![image](https://user-images.githubusercontent.com/75478893/196139159-2dcf4cb9-2bd5-4de9-99c6-e883a639f91f.png)

## Acception Criteria
- [x] Displays a title header "Start your journey"
- [x] Shows a list of upcoming trips
- [x] Every single item shows the country name and a random picture
## Tasks
- [x] Create a h1 header component with the text "Start your journey"
- [x] Create a `<ul></ul>` list wrapper for trip items
- [x] Create a state "trips" for the country items as array
- [x] Add some dummy items for the trips state as objects (`[{ id: 1, country: 'Thailand' }, { id: 2, country: 'Philippines' }]`)
- [x] Create a list item component that accepts a name property
- [x] Display every single item component based on the trips state inside the trip list wrapper
- [x] Show a random picture (unsplash) and the country name for each item

**Comment by F-Kirchhoff** [comment]
This is a very good first user story. Very good scope, good detail in acceptance criteria and tasks. The only thing I have problems to understand is the third criteria. What do you mean by that?

**Comment by sebsch1337** [comment]
Thanks for the information about the third criteria. It was indeed a confusing copy of the criteria "Shows a list of upcoming trips". I just deleted it.
