### ISSUE TITLE
add to-do item

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#20]
## Value Proposition
As a user, I want to add a to-do to my list so that i can plan what to do at the destination.
## Description
<img width="335" alt="image" src="https://user-images.githubusercontent.com/75478893/197410029-2a0609d3-dc85-4a0f-b88f-149173de9f92.png">

## Acception Criteria
- [x] A form that includes an input field with the placeholder "New to-do..."
- [x] and an add button next to the input field
- [x] Adds the new to-do item as object to the ToDos array

## Tasks
- [x] Create a form in the to-do-section of the details page
- [x] Create a styled submit button component with an icon and add it to the form
- [x] Create a styled input component and add it to the form
- [x] Add aria-labels to the form elements to make sure its accessible
- [x] Create a function that adds the new to-do object to the toDos array
- [x] Create an onSubmit event listener for the form that calls the add-function

**Comment by PhilippWeiss85** [comment]
Hi Sebastian, LGTM!
