### ISSUE TITLE
show durations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#22]
## Value Proposition
As a user, I want to see the durations for trips (in days) and their destinations (in nights) so that i know how many vacation days i have to take.
## Description
<img width="557" alt="image" src="https://user-images.githubusercontent.com/75478893/197493920-efff09e9-57b7-4648-8b7a-f630b093508c.png">

## Acception Criteria
- [ ] Shows the total number of days of all destinations on the destinations page including first day
- [ ] Shows the total number of nights of the single destination on it's details page
## Tasks
- [x] Create a function, that returns the difference between the destination startDate and endDate in days
- [x] On details page create a label "Duration" in footer bar
- [x] Below the label, return the value of the calculate-function and add "nights"
- [x] Create a function that returns the difference between the first date and last date (adding 1 day for the 1st day) as days
- [x] On destinations page create a label "Total duration" in footer bar
- [x] Below the label, return the value of the total-calculate-function and add "days"

**Comment by Mark-Krensel** [comment]
Seems like a good compact user story :)

**Comment by Mark-Krensel** [comment]
hm, maybe one thought on your first task: if i start today and return tomorrow -> you would have a 1-day trip calculating as described. I guess that should be 2 days?

**Comment by sebsch1337** [comment]
Correct, in Task 4 there will be the 1st day included. I'll describe it more precise :)
