### ISSUE TITLE
edit date form

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#25]
## Value Proposition
As a user, I want to edit the destination's dates so i can plan my duration of staying there.

## Description
<img width="336" alt="image" src="https://user-images.githubusercontent.com/75478893/197752571-495aea1f-017e-481d-9d98-9756de5a8c1f.png">

## Acception Criteria
- [x] A form in a modal component with blurry background overlay
- [x] Has a Save button
- [x] A Title named "Dates"
- [x] A label for Start Date and End Date
- [x] An input with date picker for Start Date and EndDate
- [x] Saves the changes into the destinations object

## Tasks
- [x] On details page add an edit-icon-button behind the "Dates" label
- [x] The edit button set the state-object "modal" to {visible: true, name: "Dates"}
- [x] Create a form component
- [x] Create a label and input with date picker for Start Date
- [x] Create a label and input with date picker for End Date
- [x] Create a submit button component
- [x] Add accessibility tags to form components
- [x] Create a function that saves the dates to the destinations object
- [x] Create an onClick event-listener to the save button that calls the save-function
- [x] Create a condition that puts the form component inside the modal component on details page to be shown together

**Comment by Kheirah** [comment]
Looking good!

Just curious, what do you mean by this
`Create a condition that puts the form component inside the modal component on details page to be shown together`?

I can't properly visualize what this entails.

Everything else is clear and detailed, and I get a pretty good picture. 👍

**Comment by sebsch1337** [comment]
Thanks for your review!

The form component will be displayed inside an already existing template-modal. When the state-object of the modal is set to "true" including the name of the form (e.g. {visible: true, name: "Dates"), the modal will be shown with this dates form.

Modal: https://github.com/sebsch1337/capstone-project/issues/26

**Comment by Kheirah** [comment]
Ah I see, alrighty then! Green light ahead🟢
