### ISSUE TITLE
show modal

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#26]
## Value Proposition
As a developer, I want to create a reusable modal so that i can use it for my future form components.
## Description
<img width="346" alt="image" src="https://user-images.githubusercontent.com/75478893/197746821-47296a27-86fa-44fc-8c0b-1ebdf8aa35ee.png">

## Acception Criteria
- [x] A blurry background overlay
- [x] A modal background box
- [x] Shows a Title given by prop name
- [x] Clicking on the blurry background closes the modal
- [x] Showing the children inside the modal box

## Tasks
- [x] Create a "Modal" component
- [x] Create a blurry overlay for the background
- [x] Create a box for the content
- [x] Create a title that will be filled by prop name
- [x] Create a state "modal" with an object for visible: <true / false> and name: "<detail name>" 
- [x] Create a close-function that sets the visibility to false
- [x] Create an onClick eventlistener for the blurry background overlay that calls the close-function

**Comment by F-Kirchhoff** [comment]
LGTM 🦊
