### ISSUE TITLE
edit hotel and transport details

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#29]
## Value Proposition
As a user, I want to edit hotel and transport details so that i have an overview of what i already booked.

## Description
<img width="506" alt="image" src="https://user-images.githubusercontent.com/75478893/198050658-136e2d0f-a64c-4e3a-ac8f-b360ae9156f1.png">

## Acception Criteria
- [x] A modal form
- [x] A title for hotel / transport
- [x] An input text button for the description
- [x] A save button
- [x] Form validation before submit
- [x] Save button updates the according information in destinations state

## Tasks
- [x] Create a component "EditTextForm"
- [x] Create a form component
- [x] Create a controlled input named "description" with an according placeholder text
- [x] Create a state for the controlled input
- [x] Create a submit button
- [x] Add aria-tags for accessibility
- [x] Create a function "handleSubmit" that calls onUpdateDetail function with the given information
- [x] Create a form validation (check for space only) including error text "You can travel to space, but spaces only are not allowed!"
- [x] Call the form for hotel and transport inside the modal component on destination details page (edit-buttons)
