### ISSUE TITLE
"add trip" form

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#3]
## Value Proposition
As a user, I want to add a new country to my trip list, so that i can plan my next trip to a new destination.
## Description
![image](https://user-images.githubusercontent.com/75478893/196140054-ab512bc3-6968-4713-af32-089fd6687955.png)

## Acceptance Criteria
- [x] A form with a country name input
- [x] An add trip button to create a new trip based on the input
- [x] The country name is a required information to add the trip
- [x] After clicking the add trip button, the new trip will appear in the trip list

## Tasks
- [x] Create a styled form component
- [x] Create a styled text input field component for "Country"
- [x] Set the "Country" input field to required
- [x] Create a styled button component
- [x] Create a function "addTripHandler" that adds the entered data to the "trips" state on add trip button click

**Comment by CathrinTruchan** [comment]
Looks good to me :) 
Just one comment: A label for the input field would be useful. (You probably planned that, but it is not in the wireframe ;) )

**Comment by sebsch1337** [comment]
Thanks! Added a label as placeholder! :)

**Comment by philmetscher** [comment]
Cool user story. I have a question: above the form is already Thailand as an example deposited with 30 days. Where are the days set?

**Comment by sebsch1337** [comment]
The duration will be calculated in a later stage. To avoid a placeholder-component, i deleted it from here. Could be an upcoming story then :) thanks for the info!
