### ISSUE TITLE
delete destination

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#34]
## Value Proposition
As a user, I want to delete destinations so that my app will stay clean.
## Description
<img width="338" alt="image" src="https://user-images.githubusercontent.com/75478893/198636015-0f940691-93e7-4f50-ace0-aa786dcd5f40.png">

## Acception Criteria
- [x] A delete button with icon next to destination name
- [x] Click on "DELETE" button will show a "Do you really want to delete?"-modal
- [x] Clicking on "Delete" button inside the modal will delete the destination object
## Tasks
- [x] Create a styled DeleteButton component with an icon 
- [x] Add the DeleteButton to the DestinationItem component
- [x] On destinations page, write a function that deletes a destination by id
- [x] Create an onClick eventlistener for DeleteButton that opens the existing modal component with deletion-warning component
- [x] Call delete-destionation function when clicked "Delete" in modal
