### ISSUE TITLE
show state indicators

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#35]
## Value Proposition
As a user, I want to see status icons in my destination list so that i can see what i already booked and where i already set to-dos.
## Description
<img width="350" alt="image" src="https://user-images.githubusercontent.com/75478893/198892328-5e3e55ee-5af9-4c70-95c8-f54853a5b538.png">

## Acception Criteria
- [x] A status icon for each in black, when hotel / transport / to-dos are set in the regarding destination object
- [x] Status icons are grey, when no informations are given
## Tasks
- [x] Create a new component "StatusIndicators"
- [x] Drill the state destination to the component
- [x] Create 3 expressions that show the regarding icons as black when set and grey when not set
- [x] Import the new component into DestinationItem component
