### ISSUE TITLE
toggle to-do item checkbox

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#36]
## Value Proposition
As a user, I want to mark a to-do's checkbox so that i have an overview which place i already visited.
## Description
<img width="216" alt="image" src="https://user-images.githubusercontent.com/75478893/198899716-9a345dc7-a374-4557-b74f-f26a9f2ac7de.png">

## Acception Criteria
- [x] A click on a to-do item checks its checkbox
- [x] The item text will be crossed out and grey
## Tasks
- [x] Wrap a transparent button around ToDoItem components icon and description
- [x] On details page create a function onToggleToDoItem that toggles the checked state in toDos object
- [x] Pass down the function with an according id to ToDoItem component and assign it to the new button
- [x] Create aria-labels for accessibility
