### ISSUE TITLE
use external database for trips

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#38]
## Value Proposition
As a user, I want to store my trips in the cloud so that i can access my trips from any device.

## Description
< not needed >

## Acception Criteria
- [x] A database with some dummy data based on the local dummy db.js
- [x] Models for Trips, Destinations, ToDos
- [x] An API for Trips with CRUD operations
- [x] localStorage hook for trips is replaced by database
## Tasks
- [x] On mongodb.com create a new database "capstone"
- [x] Create a collection for "trips" and one for "destinations"
- [x] Insert some dummy data based on the local db.js
- [x] Install mongoose
- [x] Create a .env.local file and store the mongodb connection string to MONGODB_URI
- [x] Create a dbConnect.js in lib that handles the mongodb connection
- [x] Create models for Trips, Destinations, ToDos
- [x] Create CRUD API functions for Trips
- [x] Get Trips from API using serverside props
- [x] Change trip delete function to use api call
- [x] Create Loader to display while API fetching

**Comment by CathrinTruchan** [comment]
Nice! Very detailed :)
