### ISSUE TITLE
show trip destinations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#4]
## Value Proposition
As a user, I want to see all destinations of my trip, so that i have an overview which cities i'm going to visit.

## Description
![image](https://user-images.githubusercontent.com/75478893/196218845-b1d9a232-b008-4a49-bcb0-9751ccbc0698.png)

## Acception Criteria
- [x] Shows a list of the trip destinations (cities)
- [x] Shows the name of the city for each destination
- [x] A navigate back button (arrow icon) in the upper left corner brings you back to the list of trips

## Tasks
- [x] Create a page for destinations
- [x] Add a styled button (arrow icon) in the upper left corner that navigates back to the trips overview
- [x] Create a styled header component that displays the country name property
- [x] Create a state "destinations" on trips page with some dummy data for name, tripId
- [x] Pass the trip destinations from "destinations" state to the destination page, based on its tripId
- [x] Link the trip from the trips page to the according destination page
- [x] Create a styled list wrapper for the destination items
- [x] Create a destination item component, that displays a name
- [x] Iterate through destinations property to display all destination items inside the wrapper

**Comment by F-Kirchhoff** [comment]
Hey, this is going to be a lot of components, so be ready when you do it. You could also split this user story in two parts: first only display the date and name of destination, and then in the second step add the icons. 

Also: please specify where this page is, add a task for creating a new page, and how to navigate to it. You could add another user story before this one which introduces detail pages about trips. This would only add the detail page as the navigation mechanics.
