### ISSUE TITLE
show start dates in destination list

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#41]
## Value Proposition
As a user, I want to see the start dates in the destination list so that i have an overview when i will be in which destination.
## Description
<img width="338" alt="image" src="https://user-images.githubusercontent.com/75478893/199298766-012b7f92-f8e1-437d-84c7-7843087742b5.png">

## Acception Criteria
- [x] Shows the start date below the destination name on destinations page
- [x] The start date is formatted in browsers local format (e.g. Mo, Oct 16)
## Tasks
- [x] In DestinationItem component, create a new component "DateText" below the NameArea
- [x] Pass down the start date to DestinationItem component
- [x] Show the passed start date inside the DateText component
- [x] Format the date to show in local format

**Comment by PhilippWeiss85** [comment]
Hi Sebastian,
as always nice and clean.
