### ISSUE TITLE
component tests for lists

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#43]
## Value Proposition
As a developer, I want use automatic tests so that i can ensure that my components work properly.
## Description
< not needed >
## Acception Criteria
- [x] Component tests for destinations and trips
## Tasks
- [x] Write tests for rendering all trip and destination items
- [x] Write a test for trip text input
- [x] Write a test for destination delete button

**Comment by PhilippWeiss85** [comment]
Hey Sebastian,

nice that you are digging into testing. Seems like a really big story to me. You may split the story into a few PRs. Otherwise as always nice and clean.
