### ISSUE TITLE
login protection

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#44]
## Value Proposition
As a user, I want to protect my data store so that nobody can access my data.
## Description
<img width="343" alt="image" src="https://user-images.githubusercontent.com/75478893/199473296-06761dad-7f49-4d2b-9182-feeb86573881.png">

## Acception Criteria
- [x] Pages are login protected
- [x] If not logged in, display login to GitHub button instead of trips
## Tasks
- [x] Create api/auth/[...nextauth].js with github provider
- [x] Add oAuth App on github
- [x] Add homepage url <url>
- [x] Add authorization callback url <url>/api/auth/callback/github
- [x] Add GITHUB_ID and GITHUB_SECRET to .env.local and vercel
- [x] Add SessionProvider to pages/_app.js
- [x] Add useSession hook to all pages
- [x] Redirect to index page if session is not logged in
- [x] Create a login button component that will be shown, when not logged in
- [x] Create login functionality for login button
- [x] Change functions and database to match user email adress only

**Comment by CathrinTruchan** [comment]
Nice! Very detailed! Nothing to add :)
