### ISSUE TITLE
trip settings

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#46]
## Value Proposition
As a user, I want to open a trip settings menu, so that i can change some settings
## Description
<img width="634" alt="image" src="https://user-images.githubusercontent.com/75478893/199713529-5fb89fb9-00f8-49f3-b6fc-a193fae2298f.png">

## Acception Criteria
- [ ] A settings icon in navbar
- [ ] The click on settings icon shows a share and delete button
- [ ] The total duration component disappears while menu is active
## Tasks
- [ ] Create a settings component with icon
- [ ] Create a state showSettings(false)
- [ ] Create a function that toggles showSettings when settings icon is clicked
- [ ] Move total duration component out of screen when showSettings is true
- [ ] Move share and delete button in when showSettings is true
- [ ] Undo it, when showSettings is false
