### ISSUE TITLE
use external database for destinations / todos

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#48]
## Value Proposition
As a user, I want to store my destinations incl. todos in the cloud so that i can access them from any device.

## Description
< not needed >

## Acception Criteria
- [x] An API for destinations and todos with CRUD operations
- [x] localStorage hook replaced by database

## Tasks
- [x] Create service functions (get, delete, update, post) for mongodb CRUD operations for destinations and todos
- [x] Create API functions (get, delete, update, post) for destinations and todos
- [x] Replace localStorage functions by API calls for destinations and todos
- [x] Display Loader modal while API call
