### ISSUE TITLE
"add destination" form

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#5]
## Value Proposition
As a user, I want to add a new destination to my trip, so that i can plan the details for visiting the destination.
## Description
![image](https://user-images.githubusercontent.com/75478893/196216670-d51b447b-fb05-4c01-b064-ead3dafc9393.png)

## Acception Criteria
- [x] Displays an add destination button on destinations page
- [x] Displays an input field to enter a new destination name
- [x] It creates a new destination in the destinations list with entered name

## Tasks
- [x] Create a form with a styled add button and styled input form element
- [x] Place the form inside the destinations list (below the last destination if exists)
- [x] Create a function "addDestinationHandler", that adds a new destination with auto generated destinationId, the entered name and associated tripId to the destinations state
- [x] Show the new destination as the last item in the destination list

**Comment by F-Kirchhoff** [comment]
What do you mean by default values? You might also display two input fields next to the + button where you add the destination and date. That would not inflate this user story too much.

**Comment by sebsch1337** [comment]
My first thought was to just create a new item with default name "New Destination" on button click. To change the values you click on the name to open a new page where you can enter more details like dates, hotels, etc.
But i changed my mind to make this page more simple. I removed all the dates in this list. They will be shown in a different way (maybe as days) in the future.

**Comment by F-Kirchhoff** [comment]
This looks already very professional, I like it a lot!
