### ISSUE TITLE
logout user session

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#51]
## Value Proposition
As a user, I want log out of my session so that someone else can use the app on my phone.
## Description
<img width="339" alt="image" src="https://user-images.githubusercontent.com/75478893/201099809-792e581d-55bc-4a6f-9f9e-541ce1c52df9.png">

## Acception Criteria
- [x] When signed in, a profile picture is shown on the top right
- [x] Click on profile picture opens a box with picture, name, email and a logout button
- [x] Click on Logout button signs the user off and brings him to login screen
## Tasks
- [x] Create a button component with round boarders and profile picture inside
- [x] Create a box component with the profile picture, user name and email adress inside
- [x] Create a button component with the label "Logout"
- [x] Create a function, that signs off the nextauth user session and brings the user to login screen
- [x] Create a function that toggles the box component when clicked on profile pic
