### ISSUE TITLE
delete user account

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#53]
## Value Proposition
As a user, I want to delete my user account and all my data, so that the app has no information about me anymore.
## Description
<img width="336" alt="image" src="https://user-images.githubusercontent.com/75478893/201312956-0474158e-5c45-48bb-8e9c-c6b843fae767.png">

## Acception Criteria
- [x] A delete button in UserProfile modal
- [x] After click on delete a modal asks "Do you really want to delete your account and all your data?"
- [x] Delete function deletes user information and regarding trips / destinations / todos
- [x] After deletion, user will be signed off an lead to the login screen

## Tasks
- [x] Create a DeleteAccountButton component
- [x] Place the delete button inside the UserProfile component
- [x] Write a function that deletes all user data based on the email address
- [x] Write a delete-account-modal component with a button to acknowledge deletion
- [x] Assign the delete function, the modal, signout, and redirect to loginpage to the delete button

**Comment by gacsphere** [comment]
Hi Sebastian, 
that's a nice feature dealing personal data.
Is there any personal data saved besides the email address and the name of the user?

**Comment by sebsch1337** [comment]
No - i just save the email address. :)
