### ISSUE TITLE
clean code and styling

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#56]
## Value Proposition
As a developer, I want to keep the code clean and the styling reusable so that my code is easy to read for other developers.
## Description
< no wireframe needed >

## Acception Criteria
- [ ] Clean, stable and reusable code
- [ ] Reusable styled components
- [ ] Reduced CSS
## Tasks
- [ ] Check all the functions and other code to avoid duplicated code and keep it simple
- [ ] Check the styled components to reduce CSS or make them reusable for other components
- [ ] Fix remaining minor styling and coding bugs
