### ISSUE TITLE
show destination details

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#6]
## Value Proposition
As a user, i want to see the name, start / end date, as well as hotel and transport to the destination, so i can keep track of what i already booked.
## Description
<img width="339" alt="image" src="https://user-images.githubusercontent.com/75478893/196383811-6a092291-a2b0-4060-9d8a-e3f01eddd4ec.png">

## Acception Criteria
- [x] Shows the details like name, start date, end date, hotel and transport
- [x] A navigate back button (arrow icon) in the upper left corner brings you back to the list of destinations
## Tasks
- [x] Create a details page
- [x] Add some destinations dummy data for destinations for name, start date, end date, hotel and transport
- [x] Create a Link from destinations page to details page
- [x] Get and show destination details for this item
- [x] Add a styled button component as an arrow icon in the upper left corner that navigates back to the destinations overview

**Comment by AHen-C0de** [comment]
This story is nicely described by the tasks! :) However, the story seems very large. May it be two stories - one for the detailed page and the routing and one for the form? Also, will you make it somehow visible, that the travel details can be edited?

**Comment by sebsch1337** [comment]
The details page actually is a form page to view and edit the data. The styling just makes it a bit seemless. To make the input fields appear more editable, i'm going to add some edit-icons. Thanks :)

**Comment by sebsch1337** [comment]
I changed my mind. I'm going to add an edit-button in another story and use this story to display the data only.
