### ISSUE TITLE
basic styling

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/capstone-project#7]
## Value Proposition
As a user, I want the app to appear in minimal, neutral way, so that the background is not too bright and the text not too dark.
## Description
<img width="525" alt="image" src="https://user-images.githubusercontent.com/75478893/196363703-5ccc7935-b190-4c20-b398-7fbcbdea65b0.png">

## Acception Criteria
- [x] The background color is #fafbff
- [x] The documents text color is #121212
- [x] Neutralizes the margins and paddings of the document
 
## Tasks
- [x] Add #fafbff as --background-primary color variable in GlobalStyle.js
- [x] Add #121212 as --text-primary color variable in GlobalStyle.js
- [x] Add margin: 0 and padding: 0 to * tag in GlobalStyle.js

**Comment by kai-franke** [comment]
Very good feature. :)
I'm not sure if this story might be a bit too small?

**Comment by sebsch1337** [comment]
Thanks Kai! I added some other styling like normalizing the margins and paddings.
